T_BIT               EQU        0x20
F_BIT               EQU        0x40
I_BIT               EQU        0x80

ModeMask            EQU        0x1F

User32Mode          EQU        0x10
FIQ32Mode           EQU        0x11
IRQ32Mode           EQU        0x12
SVC32Mode           EQU        0x13
Abort32Mode         EQU        0x17
Undef32Mode         EQU        0x1B
Sys32Mode           EQU        0x1F

                    END
