.\obj\template.o: ..\App\src\template.c
.\obj\template.o: ..\App\inc\template.h
.\obj\template.o: ..\CMSIS\stm32f10x.h
.\obj\template.o: ..\CMSIS\core_cm3.h
.\obj\template.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stdint.h
.\obj\template.o: ..\CMSIS\system_stm32f10x.h
.\obj\template.o: ..\CMSIS\stm32f10x_conf.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_adc.h
.\obj\template.o: ..\CMSIS\stm32f10x.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_bkp.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_can.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_cec.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_crc.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_dac.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_dbgmcu.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_dma.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_exti.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_flash.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_fsmc.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_gpio.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_i2c.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_iwdg.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_pwr.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_rcc.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_rtc.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_sdio.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_spi.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_tim.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_usart.h
.\obj\template.o: ..\StdPeriphDrv\inc\stm32f10x_wwdg.h
.\obj\template.o: ..\StdPeriphDrv\inc\misc.h
